apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: nexus
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso.enabled }}
  sso:
    - name: Nexus Login
      # clientId: https://nexus.{{ .Values.domain }}/service/rest/v1/security/saml/metadata
      # clientId: uds-swf-nexus
      clientId: dummy-client
      redirectUris:
        - "https://nexus.{{ .Values.domain }}/saml"
      protocol: saml
      defaultClientScopes:
        - "mapper-saml-email-email"
        - "mapper-saml-username-login"
        - "mapper-saml-firstName-first_name"
        - "mapper-saml-lastName-last_name"
        - "mapper-saml-grouplist-groups"

      attributes:
        saml.client.signature: "false"
  {{- end }}
  network:
    expose:
      - service: nexus-nexus-repository-manager
        podLabels:
          app: nexus-repository-manager
        gateway: tenant
        host: nexus
        port: 8081
    allow:
      - direction: Egress
        podLabels:
          app: nexus-repository-manager
        remoteGenerated: Anywhere

      - direction: Egress
        remoteNamespace: keycloak
        remoteSelector:
          app.kubernetes.io/name: keycloak
        selector:
          app: nexus-repository-manager
        port: 8080
        description: "SSO Internal"

      - direction: Egress
        remoteGenerated: Anywhere
        selector:
          app: nexus-repository-manager
        port: 443
        description: "SSO External"

