apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: nexus
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: nexus
        podLabels:
          app: nexus
        gateway: tenant
        host: nexus
        port: 8081
    allow:
      - direction: Egress
        podLabels:
          app: nexus
        remoteGenerated: Anywhere
