variables:
  - name: FLAVOR
    default: "registry1"

tasks:
  - name: nexus-test-bundle
    description: Create the UDS bundle with Nexus and its dependencies
    actions:
      - task: nexus-package
      - task: dependency-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: dependency-package
    description: Create the Dependency Zarf Package(s)
    actions:
      - cmd: zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom

  - name: nexus-package
    description: Create the UDS Nexus Zarf Package
    actions:
      - cmd: zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor ${FLAVOR}
