tasks:
  - name: nexus-package
    actions:
      - description: Deploy the UDS Nexus Zarf Package
        cmd: zarf package deploy zarf-package-nexus-${UDS_ARCH}-*.tar.zst --confirm --no-progress

  - name: nexus-test-bundle
    actions:
      - description: Deploy the UDS bundle with Nexus and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-nexus-test-${UDS_ARCH}-*.tar.zst --confirm --no-progress
