includes:
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.2/tasks/create.yaml
  - publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.4.2/tasks/publish.yaml

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Create the AMD64 package
        task: create:package
        with:
          architecture: amd64

      - description: Publish the packages
        task: publish:package
        with:
          # x-release-please-start-version
          version: "3.66.0-uds.1"
          # x-release-please-end
