tasks:
  - name: health-check
    actions:
      - description: Nexus Deployment Health Check
        wait:
          cluster:
            kind: Deployment
            name: nexus-nexus-repository-manager
            namespace: nexus

  - name: ingress
    actions:
      - description: Nexus UI Health Check
        wait:
          network:
            protocol: https
            address: nexus.uds.dev
            code: 200
