options:
  log_level: info
shared:
  DOMAIN: uds.dev
variables:
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        nexus.nexus: []  # database owner
      databases:
        nexusdb: nexus.nexus
      version: "13"
      ingress:
        remoteGenerated: Anywhere
  nexus:
    NEXUS_DB_ENDPOINT: "pg-cluster.postgres.svc.cluster.local"
    # SSO requires a license
    NEXUS_SSO_ENABLED: false
    NEXUS_LICENSE_KEY: ""
