options:
  log_level: info
variables:
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        nexus.nexus: []  # database owner
      databases:
        nexusdb: nexus.nexus
      version: "13"
      ingress:
        remoteGenerated: Anywhere
  nexus:
    nexus_db_endpoint: "postgresql.dev-postgres.svc.cluster.local"
