name: update-images
description: "Update all findable images for all zarf packages in repo"

runs:
  using: composite
  steps:
    - name: Run script
      run: |
        ./.github/actions/update-images/update-images.sh
      shell: bash
