name: get-cluster-info
description: "Save info on cluster"

inputs:
  artifact-suffix:
    description: "Suffix to append to the artifact name"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create artifact directory
      run: |
        mkdir -p cluster-info
      shell: bash

    - name: Get Pod Logs
      run: |
        set +e
        kubectl get pods --all-namespaces -o custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace --no-headers | while read pod namespace; do
          kubectl logs --namespace=$namespace "$pod" > "cluster-info/${pod}.log"
        done
        set -e
      shell: bash

    - name: Get Pod Descriptions
      run: |
        set +e
        kubectl get pods --all-namespaces -o custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace --no-headers | while read pod namespace; do
          kubectl describe pod --namespace=$namespace "$pod" > "cluster-info/${pod}.desc"
        done
        set -e
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: cluster-info${{ inputs.artifact-suffix }}
        path: cluster-info/
