name: Update Images

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    name: Update Images

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PUSH_PAT }}

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.32.1

      - name: Iron Bank Login
        run: zarf tools registry login -u "${{secrets.IRON_BANK_ROBOT_USERNAME}}" -p "${{secrets.IRON_BANK_ROBOT_PASSWORD}}" registry1.dso.mil
        
      - name: Update Images
        uses: ./.github/actions/update-images

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git add .
            git commit -m "chore: update images"
            git push
          else
            echo "No changes to commit"
          fi
